spring:
  application:
    name: user-order
  profiles:
    active: dev  # профиль по умолчанию
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false

server:
  port: 8082

logging:
  level:
    com.example: DEBUG
    org.hibernate.SQL: DEBUG

---
# ======= DEVELOPMENT =======
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5434/user_order
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

jwt:
  secret: dev-secret-key-change-in-production-2024
  expiration: 86400000

---
# ======= PRODUCTION =======
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:user_order_prod}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # В продакшене только валидация!
    show-sql: false

jwt:
  secret: ${JWT_SECRET:prod-secret-key-change-me}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    com.example: INFO
    org.springframework: INFO